# Generated by Django 4.1.1 on 2022-10-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_logintable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='csrfmiddlewaretoken',
            field=models.TextField(null=True),
        ),
    ]
